server:
  port: ${FREEROAM_TRAILS_PORT:8100}

eureka:
  instance:
    hostname: ${FREEROAM_EUREKA_HOSTNAME:localhost}
  client:
    serviceUrl:
      defaultZone: ${FREEROAM_EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: freeroam-trails-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${FREEROAM_OAUTH2_KEYCLOAK_ISSUER_URI}

logging:
  level:
    root: warn